Design work section
ciraganenicole/Portfolio pull request #3
Opened 2022-02-11 14:52 UTC by ciraganenicole

In this pull request I:
-Design a work section
-Use grid and flex-box

2022-02-11 15:40 UTC, Amrhub requested changes
Hi @ciraganenicole,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## To Highlight ✔️ 
Highly clean and organized code 👏🏻 It was really pleasure reading your code 😄 
Professional documentation ✔️ 
correct workflow ✔️ 

It just seems like we missed a requirement where we should have implement the about me section as well 🙁 

## Required Changes ♻️
_Check the comments under the review._
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 15:40 UTC, Amrhub commented on index.html
> +    </section>
- [ ] You've implemented the `work-section` perfectly! Let's make sure that we also implement the `about-me` section since it was part of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)

2022-02-12 04:51 UTC, ciraganenicole commented
> Hello @ciraganenicole 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Hi, kindly apply all the required sections in one pull request and submit that pull request for review this would enable proper code review and GitHub review features, you can only close or merge a pull request when it has been approved.
> 
> As this was the only reason that your project was not approved it will be approved as soon as possible. Please note that since we will approve it manually so this could take a few hours!
> 
> Keep rocking 🚀! // can be customized

Hi @Davidosky007 
Thanks for understanding 
Now, where do I have to send my pull request again?

2022-02-12 05:17 UTC, Davidosky007 commented
> > Hello @ciraganenicole 👋,
> > _This is an additional review as a result of the second opinion request._
> > Hi, kindly apply all the required sections in one pull request and submit that pull request for review this would enable proper code review and GitHub review features, you can only close or merge a pull request when it has been approved.
> > As this was the only reason that your project was not approved it will be approved as soon as possible. Please note that since we will approve it manually so this could take a few hours!
> > Keep rocking 🚀! // can be customized
> 
> Hi @Davidosky007 Thanks for understanding Now, where do I have to send my pull request again?

Your project would be approved manually just be patient 🙏

2022-02-12 11:34 UTC, merged