Responsiveness
ciraganenicole/Portfolio pull request #5
Opened 2022-02-16 19:26 UTC by ciraganenicole

In this pull request I:
- Use media queries to set up responsiveness

2022-02-16 20:12 UTC, thecodechaser requested changes
## Hi @ciraganenicole 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ]  To make your README file more professional add some screenshot of your design.
- [ ] Check the optional suggestions comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 20:12 UTC, thecodechaser commented on index.html
> +        <section class="My-Works">
- [ ] On the desktop screen project section should show only 3 projects per row but right now it is showing 4 projects, Please fix the issue and make sure your project section only shows 3 projects per row and matches the design on the template.

Your design

![Screenshot (140)](https://user-images.githubusercontent.com/83803414/154346247-3bbedc3e-45a6-40e7-9bbc-1fec4835bc06.png)


Figma design

![Screenshot (141)](https://user-images.githubusercontent.com/83803414/154346220-142306fe-c327-46ec-a087-b75049606eae.png)

2022-02-16 20:12 UTC, thecodechaser commented on index.html
> +        <div class="desktop">
- [ ] Your contact section should be in the center, Right now it is aligned to the left. Please align your contact section in the center and make sure it matches the design on the template.

Your design

![Screenshot (147)](https://user-images.githubusercontent.com/83803414/154347021-7bad5ccd-339a-4998-a806-7e2a546152d7.png)


Figma design

![Screenshot (144)](https://user-images.githubusercontent.com/83803414/154346708-1cbb8654-bc60-4e66-af30-20dcde609c4d.png)

2022-02-16 20:12 UTC, thecodechaser commented on index.html
>      <section class="contact-form">
- [ ] [optional] Instead of `<section>` element here, Please use `<footer>` tag. It will make sure your code is semantic and follows HTML best practices.

2022-02-16 20:12 UTC, thecodechaser commented on index.html
> +        </header>
- [ ] [optional] A webpage should only have one `<header>`. Please remove the second header. It will make sure your code is semantic and follows HTML best practices.

2022-02-17 13:04 UTC, keroloussamy requested changes
Hi @ciraganenicole, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 13:04 UTC, keroloussamy commented on style.css
>  .about {
- [ ] As the previous reviewer asked, Kindly check here the background images they don't appear at any width.

![image](https://user-images.githubusercontent.com/35535130/154486533-c31f6d10-0389-4f8f-9192-bf6941671e74.png)

2022-02-17 13:04 UTC, keroloussamy commented on style.css
> +  }
- [ ]  As the previous reviewer asked, Kindly recheck the image here, because it doesn't appear, with width more than 1000 width.

![image](https://user-images.githubusercontent.com/35535130/154487327-bcf682a9-1662-41d7-a22e-23ae9804c93b.png)

2022-02-17 14:56 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @ciraganenicole,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 14:59 UTC, merged